controller_list:
  - name: fake_HH020_motion_controller
    type: $(arg fake_execution_type)
    joints:
      - lower_joint
      - upper_joint
      - arm_joint
      - wrist_R2_joint
      - wrist_B_joint
      - wrist_R1_joint
initial:  # Define initial robot poses per group
#  - group: HH020_motion
#    pose: home

  []