HH020_motion_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lower_joint
    - upper_joint
    - arm_joint
    - wrist_R2_joint
    - wrist_B_joint
    - wrist_R1_joint
  gains:
    lower_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_R2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_B_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_R1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1