controller_list:
  - name: HH020_motion_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - lower_joint
      - upper_joint
      - arm_joint
      - wrist_R2_joint
      - wrist_B_joint
      - wrist_R1_joint